# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('article_type', models.CharField(max_length=128, verbose_name='版块名称')),
            ],
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.ArticleType', verbose_name='版块'),
        ),
    ]
