# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20170902_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=128, verbose_name='版块名称')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'OpenStack'), (4, 'GoLang')], default=None),
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
