# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20170902_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(max_length=128, verbose_name='头像'),
        ),
    ]
