# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20170903_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTheme',
            fields=[
                ('nid', models.BigAutoField(primary_key=True, serialize=False)),
                ('themename', models.CharField(max_length=32, verbose_name='主题名称')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.BlogTheme', verbose_name='博客主题'),
        ),
    ]
