# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20170903_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='urls',
            field=models.CharField(max_length=168, null=True, verbose_name='个人博客网址'),
        ),
    ]
